### ISSUE TITLE
Post Meetings notes and clean Github Reps Call issues

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/Reps#222]
## Goal:
- Post all the weekly reps call's meeting notes
- Clean up the Github issues related to them

## Meetings 
- [x] #153 - Reps Weekly Call - April 6th, 2016 - [notes](https://discourse.mozilla-community.org/t/weekly-call-06-04-2017/14857/2?u=ioana)
- [x] #156 - Reps Weekly Call - April 13th, 2016 - [notes](https://discourse.mozilla-community.org/t/weekly-call-13-04-2017/15034/2)
- [x] #160 - Reps Weekly Call - April 20th, 2017 - [notes](https://discourse.mozilla-community.org/t/weekly-call-20-04-2017/15145/2)
- [x] #165 - Reps Weekly Call - April 27th, 2017 - [notes](https://discourse.mozilla-community.org/t/weekly-call-27-04-2017-special-activate-call/15275/3)
- [x] #166 - Reps Weekly Call - May 4th, 2017 - [notes](https://discourse.mozilla-community.org/t/weekly-call-04-05-2017/15409/2)
- [x] #167 - Reps Weekly Call - May 11th, 2017 - [notes](https://discourse.mozilla-community.org/t/weekly-call-11-05-2017/15542/2)
- [CANCELLED] Reps Weekly Call - May 18th, 2017
- [x] #182 - Reps Weekly Call - May 25th, 2017 - [notes](https://discourse.mozilla-community.org/t/weekly-call-25-03-2017-special-call/15847/3)
- [CANCELLED] Reps Weekly Call - June 1st , 2017
- [x] #184 - Reps Weekly Call - June 8th, 2017 - [notes](https://discourse.mozilla-community.org/t/weekly-call-08-06-2017/16156/2)
- [x] #185 - Reps Weekly Call - June 15th, 2017 - [notes](https://discourse.mozilla-community.org/t/weekly-call-15-06-2017/16331/2)
- [x] #186 - Reps Weekly Call - June 22nd, 2017 - [notes](https://discourse.mozilla-community.org/t/weekly-call-22-06-2017/16609/2)
- [x] Reps Weekly Call - July 6th, 2017  - [notes](https://discourse.mozilla-community.org/t/weekly-call-06-07-2017/16893/3)
- [x] Reps Weekly Call - July 13th, 2017  - [notes](https://discourse.mozilla-community.org/t/weekly-call-13-07-2017/17060/3)
- [x] #220 - Reps Weekly Call - July 20th, 2017 - [notes](https://discourse.mozilla-community.org/t/weekly-call-20-07-2017/17237/3)

**Comment by ioana-chiorean** [comment]
All notes are up. 
All github issues close.

Have a great weekend everyone!
