### ISSUE TITLE
Reps Newsletter

### ISSUE THREAD

**Issue by yomanpatil** [mozilla/Reps#341]
# Newsletter for the month of August 2018
## Tasks: 

- [x] Co-ordinate with Newsletter team
- [x] Host monthly call with the team
- [x] Pass Council Updates to team
- [x] Drafting content
- [x] Getting content reviewed from the Council
- [x] Make announcement on Discourse
- [x] Post Newsletter
- [x] Check Performance (How many reps viewed the newsletter)

## Roles:

Responsible: Ganesh, Ruwan

Accountable: @yomanpatil

Supporting: @prathameshchavan

**Comment by MichaelKohler** [comment]
@yomanpatil What's the status here?

**Comment by yomanpatil** [comment]
Reach on the Sep Newsletter: 
2 - replies
123 - Views
2 - users
10 - likes
8 - links

**Comment by yomanpatil** [comment]
# Newsletter for the month of October 2018
## Tasks 
- [ ] Co-ordinate with Newsletter team
- [ ] Host monthly call with the team
- [ ] Pass Council Updates to team
- [ ] Drafting content
- [ ] Getting content reviewed from the Council
- [ ] Make announcement on Discourse
- [ ] Post Newsletter
- [ ] Check Performance (How many reps viewed the newsletter)

## Roles:

Responsible: @gangit, @ruwan-ranganath
Accountable: @yomanpatil

**Comment by gangit** [comment]
Noted with thanks. The tasks continue!

**Comment by MichaelKohler** [comment]
@yomanpatil would it make sense to create an issue per month instead of gathering everything in one here?

**Comment by yomanpatil** [comment]
@MichaelKohler  Yes I was thinking the same. Otherwise the newsletter issue will remain open always :D

**Comment by kelimuttu** [comment]
Should we close this one @yomanpatil ?

**Comment by yomanpatil** [comment]
Yes we can.
