### ISSUE TITLE
Newsletter for the month of October 2018

### ISSUE THREAD

**Issue by yomanpatil** [mozilla/Reps#353]
# Newsletter for the month of October 2018
## Tasks: 

- [x] Co-ordinate with Newsletter team
- [x] Host monthly call with the team
- [x] Pass Council Updates to team
- [x] Drafting content
- [x] Getting content reviewed from the Council
- [x] Make announcement on Discourse
- [x] Post Newsletter
- [x] Check Performance (How many reps viewed the newsletter)

## Roles:

Responsible: Ganesh, Ruwan

Accountable: @yomanpatil

**Comment by yomanpatil** [comment]
Reach on the Oct Newsletter:

replies - 3
views - 101
users - 4
likes - 10
