### ISSUE TITLE
(2019 H1 - O1) "Mozillian of Month" experiment

### ISSUE THREAD

**Issue by irvin** [mozilla/Reps#371]
## Goal: 

Evolve long idle Rep of the Month (ROM) into “(Mission Driven) Mozillian of the Month”

### Plan: 
1. At the end of the each month (w4), we post on Discourse to ask Rep to reply and

    1) Nominate local Mozillian who did good on either Mozilla projects or other open source projects during last month, 
    2) Tell us what the Mozillian did and how they (Rep) helping / facilitating / co-working with the nominee.

2. After 10 days of nominate (w1.5), we ask Reps to vote for the best Mozillian and their following Rep.

3. At the 4th week, we highlight Mozillian of the Month and the Rep on Discourse, and ask for next round of nominate.

#### Additional 
1. We ask tl;dr team and monday meeting to honor Mozillian of Month.
2. We also want others at Mozilla knowing Rep, “Mozillians of the Month” can be a good project to bridge and promote rep to other teams.

## Related Issues & Links: 
https://docs.google.com/document/d/1fFhukjuBF03LM-weZWBN6biO_LcwO1zhyqEZ4hr8qfI/edit
[Reference meta issues and past issues] #

## Roles:

Responsible: Irvin

Accountable:

Supporting:

Consulted:

Informed: 

## Required: 

- [ ] <del>Release the idea and rule to Discourse, promote with multiple channels, asking for Rep’s feedback.</del> (Irvin, Due: )
- [x] (4th week of month) [Ask rep to start nominate for the first time](https://discourse.mozilla.org/t/announcing-mozillian-of-the-month-february-experiment-nominating-until-3-7/36190) (Irvin, Due: , Done: 2/25 )
- [x] [Announcement on Discourse Mozillians board](https://discourse.mozilla.org/t/announcing-mozillian-of-the-month-february-experiment-event/36191) (Irvin, Due: , Done: 2/25 )
- [x] [Add a nominating example](https://discourse.mozilla.org/t/nominating-mozillian-of-the-month-ett-chung/36192) (Irvin, Due: , Done: 2/25 )
- [x] Promoting on Telegram (Irvin, Due: , Done: 3/5)
- [x] Promoting on Reps-general mailing list (Irvin, Due: , Done: 3/5)
- [x] (1.5 weeks later) Start the [voting procedure on Discourse](https://discourse.mozilla.org/t/voting-for-mozillian-of-the-month-february-ended/36673/) open to all Mozillian (Irvin, Due: 3/8 16:00 UTC)
- [x] (w4) [Announce winner of Mozillian of the Month](https://discourse.mozilla.org/t/pranshu-khanna-mozillian-of-the-month-february-2019/37213/) with the following Rep (Irvin, Due: 3/18, 15:00 UTC)
- [x] (w4) Discuss and decide if we want to do again with Council (owner: Irvin, Due: )
- [x] (w4) Gather shipping info (Irvin, Due:, Done:)
- [ ] (w5) Send the swag to Winner and Nominator (owner: @kelimuttu , Due:, Done: )
- [x] (w5) [Pinning TL;dr](https://mozilla.slack.com/archives/CGHMHTJVA/p1553622176004200) about Mozillian of February (owner: Irvin, Due:, Done: 3/27)

### The timeline for second round

- [x] (4th week of month) [Ask rep to start nominate for March](https://discourse.mozilla.org/t/nominate-for-mozillian-of-the-month-march-starts-until-4-6/37441) (Irvin, Due: 3/23 , Done: 3/27)
- [x] [Promoting on Telegram](https://github.com/mozilla/Reps/issues/371#issuecomment-478243618) (Irvin, Due: , Done: 3/27)
- [x] [Announce last winner and promoting nonimate on Reps-general mailing list](https://github.com/mozilla/Reps/issues/371#issuecomment-478243480) (Irvin, Due: , Done: 3/27)
- [x] [Call for nominating on Twitter](https://twitter.com/mozillareps/status/1112039397577449472) (Irvin, Due: , Done: 3/30)
- [x] (1.5 weeks later) [Start the voting procedure on Discourse open to all Mozillian](https://discourse.mozilla.org/t/voting-for-mozillian-of-the-month-march-end-4-21-15-00-utc/37870/6) (Irvin, Due: 4/7 15:00 UTC, Done: 4/7)
- [x] [Call for voting on Discourse Rep category](https://discourse.mozilla.org/t/voting-for-mozillian-of-the-month-march-starts-now/37871/) (Irvin, Due: 4/7 15:00 UTC, Done: 4/7)
- [x] [Call for voting on Telegram Rep channel](https://discourse.mozilla.org/t/voting-for-mozillian-of-the-month-march-end-4-21-15-00-utc/37870/) (Irvin, Due: 4/7, Done: 4/7)
- [x] [Call for voting on Telegram Mozillian channel](https://t.me/mozillian/39335) (Irvin, Due: 4/7, Done: 4/7)
- [ ] Call for voting on Slack Random channel (Irvin, Due: 4/14, Done: )
- [x] [Call for voting on Twitter MozillaRep](https://twitter.com/mozillareps/status/1119281241801535488) (Irvin, Due: 4/14, Done: 4/19)
- [x] (w4) [Announce winner of Mozillian of the Month](https://discourse.mozilla.org/t/diky-arga-mozillian-of-the-month-march-2019/38570/2) with the following Rep (Irvin, Due: 4/21, 15:00 UTC, Done: 4/23)
- [x] [Announce the winner on Rep Telegram](https://t.me/c/1020212813/23785) (Irvin, 4/30)
- [x] [Announce the winner on Mozillian Telegram](https://t.me/mozillian/39626) (Irvin, 4/24)
- [x] [Announce the winner on Rep Twitter](https://github.com/mozilla/reps-tweets/issues/99)
- [x] [Announce the winner on Slack Random](https://mozilla.slack.com/archives/C027LFU26/p1556555419308200) (Irvin, 4/30)
- [x] (w4) Collect [the stats](https://docs.google.com/document/d/1X_-mVXc0tNrbLK_nZZK2EMJZOgCjBLPO4K3UJZ0ZbgY/edit#heading=h.dzo7c9vvr20c) (owner: Irvin, Due: 4/22, Done: )
- [x] (w4) Discuss and decide if we want to do again with Council (owner: Irvin, Due: 4/23)
- [ ] (w5) Send the swag to Winner and Nominator (owner: @kelimuttu , Due: , Done: )

### The timeline for third round
- [x] (4th week of month) [Ask rep to start nominate for April](https://discourse.mozilla.org/t/nomination-for-mozillian-of-the-month-april-starts-now-until-5-8/38795) (Irvin, Due: 4/29 , Done: )
- [x] [Promoting on Telegram](https://t.me/c/1020212813/23785) (Irvin, Due: , Done: 4/30)
- [x] [Announce last winner and promoting nonimate on Reps-general mailing list](https://lists.mozilla.org/private/reps-general/2019-May/002423.html) (Irvin, Due:, Done: 5/2)
- [ ] [Promoting nonimate on Mozillians mailing list]() (Irvin, Due:, Done: )
- [x] [Call for nominating on Twitter Reps](https://github.com/mozilla/reps-tweets/issues/100) (Irvin, Due: , Done: 5/4)
- [x] [Call for nominating on Rep Telegram again](https://t.me/c/1020212813/23837) (Irvin, Due: , Done: 5/7)
- [x] (1.5 weeks later) [Start the voting procedure on Discourse open to all Mozillian](https://discourse.mozilla.org/t/voting-for-mozillian-of-the-month-april-end-5-26-15-00-utc/40148/) (Irvin, Due: 5/9 15:00 UTC, Done: 5/9 17:00)
- [x] [Call for voting on Telegram Rep channel](https://t.me/c/1020212813/23880) (Irvin, Due: , Done: 5/9)
- [x] [Call for voting on Discourse Rep category](https://discourse.mozilla.org/t/voting-for-mozillian-of-the-month-april-now/40341) (Irvin, Due: , Done: 5/14)
- [x] [Call for voting on Telegram Mozillian channel](https://t.me/mozillian/40308) (Irvin, Due: , Done: 5/14)
- [x] [Call for voting on Slack Random channel](https://mozilla.slack.com/archives/C027LFU26/p1557842642084800) (Irvin, Due: , Done: 5/14)
- [x] [Prepare draft to send on Mozillian mailing list call for voting](https://docs.google.com/document/d/102d9EGI6ziBSX_kztVyjl6lILJV0BWeo7Ov3j-hbYX0/edit?usp=sharing) (Irvin, Due: 5/20, Start: 5/14, Done: 5/17)
- [x] [Call for voting on Twitter MozillaRep](https://github.com/mozilla/reps-tweets/issues/102) (Irvin, Due: , Done: 5/15)
- [x] Send out [Mozillian call for voting mail](https://www.evernote.com/l/AIBdU-1mKn1NlrBiaaXb66ui3cFJJcOKo2A) (Konstantina, Due: 5/22, Done: 5/23)
- [x] [Call for voting on Telegram Rep channel again](https://t.me/c/1020212813/24009) (Irvin, Due: 5/21 , Done: )
- [x] [Call for voting on Telegram Mozillian channel again]() (Irvin, Due: , Done: 5/21)
- [x] Call for vote on old Discourse voting thread [1](https://discourse.mozilla.org/t/voting-for-mozillian-of-the-month-february-ended/36673/9) [2](https://discourse.mozilla.org/t/voting-for-mozillian-of-the-month-march-ended/37870/7) (Irvin, Due:, Done: )
- [x] (w4) [Announce winner of Mozillian of the Month](https://discourse.mozilla.org/t/allen-wang-mozillian-of-the-month-april-2019/40906) on Discourse Rep (Irvin, Due: 5/26, 15:00 UTC, Done: 5/28)
- [x] [Announce the winner on Rep Telegram](https://t.me/c/1020212813/24036) (Irvin, Done: 5/28)
- [x] [Announce the winner on Mozillian Telegram](https://t.me/mozillian/40529) (Irvin, Done: 5/28)
- [ ] Announce the winner on Rep Twitter
- [ ] Announce the winner on Slack Random
- [ ] [Create a certification template for MoM winner]() (Irvin, Due: 5/25 , Dome:)
- [ ] (w4) Collect [the stats](https://docs.google.com/document/d/1X_-mVXc0tNrbLK_nZZK2EMJZOgCjBLPO4K3UJZ0ZbgY/edit#heading=h.dzo7c9vvr20c) (owner: Irvin, Due: , Done: )
- [ ] (w4) Discuss and decide if we want to do again with Council (owner: Irvin, Due: )
- [ ] (w5) Send the swag to Winner and Nominator (owner: @kelimuttu , Due: , Done: )

**Comment by irvin** [comment]
The announce on Telegram group
<img width="904" alt="2019-03-06 1 29 57" src="https://user-images.githubusercontent.com/165936/53824807-c47f1400-3faf-11e9-9103-df41a25c050f.png">

The announce on reps-general
<img width="742" alt="2019-03-06 1 31 59" src="https://user-images.githubusercontent.com/165936/53824824-d19c0300-3faf-11e9-975c-78908428c12e.png">

**Comment by irvin** [comment]
backup: Email content about the announcement of Mozillian of February and nomination start for March 

--
# Announce Mozillian of February and start nominate Mozillian of the March until Apr 6

Hi Reps,

Please join us to congratulate Pranshu Khanna, the Mozillian of the Month February (2019) 

Pranshu has been a Mozillian in the Mozilla India community since 2016. In February, he wrapped up the Privacy Month campaign with the social media and design, spoke at three A-frame and extensions workshops. 
Read the whole story and congratulate him at here - https://discourse.mozilla.org/t/pranshu-khanna-mozillian-of-the-month-february-2019/37213/

And thanks to Shina Dhingra, the Rep who nominated him.


And the next round starts today.
Please nominating Mozillian who did great in past month at your local community, by April 6 (15:00 UTC), following the format in this topic - https://discourse.mozilla.org/t/nominate-for-mozillian-of-the-month-march-starts-until-4-6/37441/

Let's make the contributor visible!


Irvin
On behalf of Reps Council

**Comment by irvin** [comment]
backup: announce nominating start for march on Telegram
--
Hi Reps, Please start nominating Mozillian of the Month (March)! 
https://discourse.mozilla.org/t/nominate-for-mozillian-of-the-month-march-starts-until-4-6/37441

**Comment by irvin** [comment]
# February threads

(Reps)

- Call for nominating https://discourse.mozilla.org/t/announcing-mozillian-of-the-month-february-experiment-nominating-until-3-7/36190/
- Call for voting https://discourse.mozilla.org/t/voting-for-mozillian-of-month-february-starts-now/36675/
- Nominating 1 https://discourse.mozilla.org/t/nominating-mozillian-of-the-month-ett-chung/36192/
- Nominating 2 https://discourse.mozilla.org/t/nominating-mozillian-of-the-month-pranshu-khanna/36396/
- Nominating 3 https://discourse.mozilla.org/t/nominating-mozillian-of-the-month-saverio-morelli/36525/

(Mozillians)

- Announce campaign https://discourse.mozilla.org/t/announcing-mozillian-of-the-month-february-experiment-event/36191/
- Voting https://discourse.mozilla.org/t/voting-for-mozillian-of-the-month-february-ended/36673/
- Announce Winner https://discourse.mozilla.org/t/pranshu-khanna-mozillian-of-the-month-february-2019/37213/

# March threads

(Reps)

- Call for nominate https://discourse.mozilla.org/t/nominate-for-mozillian-of-the-month-march-starts-until-4-6/37441/
- Call for voting https://discourse.mozilla.org/t/voting-for-mozillian-of-the-month-march-starts-now/37871/
- Nominating 1 https://discourse.mozilla.org/t/nominating-mozillian-of-the-month-diky-arga/37787/
- Nominating 2 https://discourse.mozilla.org/t/nominating-mozillian-of-the-month-mario-garcia/37745/
- Nominating 3 https://discourse.mozilla.org/t/nominating-mozillian-of-the-month-sara-todaro/37535/
- Nominating 4 https://discourse.mozilla.org/t/nominating-mozillian-of-the-month-syamkumar/37770/

(Mozillians)

- Voting https://discourse.mozilla.org/t/voting-for-mozillian-of-the-month-march-end-4-21-15-00-utc/37870/
- Announce Winner https://discourse.mozilla.org/t/diky-arga-mozillian-of-the-month-march-2019/38570/

**Comment by irvin** [comment]
The swag for first and second round still haven't send out. It's been blocked within Mozilla internal bug on vendor procedure.

**Comment by ioana-chiorean** [comment]
Updates here? Are we keeping the same open or we should maybe open each month a new one?

**Comment by irvin** [comment]
I think we should open a new one for next quarter. I will close this once we have a new one.

**Comment by irvin** [comment]
closed with following plan #384
