### ISSUE TITLE
"Mozillian of Month" for Q3 2019

### ISSUE THREAD

**Issue by irvin** [mozilla/Reps#387]
## Goal: 
Mozillian of the Month is an experiment monthly recognition campaign, ran by Irvin from February to April. It’s goal is to encourage Reps to take a leadership role and help local Mozillians to be visible. 

We ask Reps to nominate local volunteers who did well in last month, by posting their story on Discourse Rep and Mozillians categories, and let all Mozillians to vote for the best-love Mozillian each month. The winner and the nominator will receive small swag.

### Plan: 
1. At the end of the each month (w4), we post on Discourse to ask Rep to reply and

    1) Nominate local Mozillian who did good on either Mozilla projects or other open source projects during last month, 
    2) Tell us what the Mozillian did and how they (Rep) helping / facilitating / co-working with the nominee.

2. After 10 days of nominate (w1.5), we ask Reps to vote for the best Mozillian and their following Rep.

3. At the 4th week, we highlight Mozillian of the Month and the Rep on Discourse, and ask for next round of nominate.

#### Additional 
1. We honor Mozillian of Month winner on Discourse, Rep Newsletter and Mozilla Slack. 
2. We want others at Mozilla to know about Rep. “Mozillians of the Month” can be a good way to bridge and promote reps and volunteers to other teams.

## Related Issues & Links: 
https://discourse.mozilla.org/search?q=%22Mozillian%20of%20the%20month%22
#371 
#384 

## Roles:
Responsible: Irvin / Mozillian of the Month Team

**Comment by irvin** [comment]
## August round action items

### Nominate (1st week of August)

- [x] [Ask rep to start nominate for July Mozillian of the Month](https://discourse.mozilla.org/t/nomination-for-mozillian-of-the-month-july-starts-until-8-10/43338) (@shinadhingra18, Due: 8/3, Done: 8/3 )
- [x] [Promoting on Rep Telegram channel](https://t.me/c/1020212813/24581) (@shinadhingra18, Due: 8/5, Done: 8/5)
- [x] [Promoting on Reps-general mailing list](https://lists.mozilla.org/private/reps-general/2019-August/002449.html) (@smsnobin77, Due:  8/5, Done: 8/8)
- [x] [Call for nominating on Twitter MozillaReps](https://github.com/mozilla/reps-tweets/issues/104) (@smsnobin77, Due: 8/5, Done: 8/8)

### Vote (1.5 weeks later)

- [x] Start the [voting procedure on Discourse #Mozillian](https://discourse.mozilla.org/t/voting-for-mozillian-of-the-month-july-due-8-25-15-00-utc/43730) open to all Mozillian (@irvin, Due: 8/12 15:00 UTC, Done: 8/12 17:00 UTC)
- [x] Link back to voting thread from nominating thread (@irvin, Due: 8/13, Done: 8/13)
- [x] [Call for voting on Discourse #Rep category](https://discourse.mozilla.org/t/vote-for-mozillian-of-the-month-july-before-sunday/44182) (@irvin, Due: 8/18, Done: 8/22)
- [x] Call for voting on Rep's call (@shinadhingra18, Done: 8/16)
- [x] [Call for voting on Telegram Rep channel](https://t.me/c/1020212813/24596) (@smsnobin77, Due: 8/18, Done: 8/13 )
- [x] [Call for voting on Telegram Mozillian channel]()(@smsnobin77, Due: 8/18, Done: 8/13)
- [x] [Call for voting on Slack Random channel](https://mozilla.slack.com/archives/C027LFU26/p1566408199282500) (@irvin, Due: 8/18, Done: 8/22)
- [ ] Call for voting on Twitter MozillaRep (, Due: 8/22, Done: )
- [ ] Call for voting on Telegram Rep channel again (, Due: 8/21, Done: )
- [ ] Call for voting on Telegram Mozillian channel again (, Due: 8/21, Done: )


### Announce (w4)

- [x] [Announce winner of Mozillian of the Month](https://discourse.mozilla.org/t/harsh-mehta-mozillian-of-the-month-july-2019/44307) and the following Rep's story on Discourse (@irvin, Due: 8/26, 15:00 UTC)
- [x] [Links to announce of Mozillian of the Month](https://discourse.mozilla.org/t/voting-for-mozillian-of-the-month-july-end-at-8-25-15-00-utc/43730/6) on voting thread (@irvin, Done: 8/27)
- [x] [Vouch fro the winner on Mozillians](https://mozillians.org/zh-TW/u/obitodarky/) (if not have 3 yet) (@irvin, Done: 8/27)
- [x] [Announce the winner on Rep Telegram](https://t.me/c/1020212813/24654) (@smsnobin77, Due: 8/29, Done: 8/27)
- [x] [Announce the winner on Mozillian Telegram](https://t.me/mozillian/41646) (@smsnobin77 , Due: 8/29, Done: 8/27)
- [x] [Announce the winner on Rep Twitter](https://github.com/mozilla/reps-tweets/issues/105)(@smsnobin77 , Due: 8/29, Done: 8/31)
- [x] [Announce the winner on Slack Random](https://mozilla.slack.com/archives/C027LFU26/p1567524322091800) (Irvin, Due: 8/29, Done: 9/3)
- [x] Collect swag shipping info from Pranshu (@irvin, Done: 9/3)
- [ ] Send the swag to Winner and Nominator (owner: @kelimuttu, Done: )
- [ ] Create a certification template for MoM winner (Irvin, Due: 9/1 , Dome:)
- [ ] Collect [the stats](https://docs.google.com/document/d/1X_-mVXc0tNrbLK_nZZK2EMJZOgCjBLPO4K3UJZ0ZbgY/edit#heading=h.dzo7c9vvr20c) (owner: Irvin, Due: 9/1, Done: )
- [x] [Start new Github thread](#issuecomment-524942234) (owner: Irvin, Due: 8/27, Done: 8/27)

### Additional

- [ ] [Draft blogpost to introduce Mozillian of Month campaign]() (@bobreyes, Due: 8/11, Done: )

**Comment by irvin** [comment]
## September action items

### Nominate (4th week of August)

- [x] [Ask rep to start nominate for August Mozillian of the Month](https://discourse.mozilla.org/t/nomination-for-mozillian-of-the-month-august-starts-until-9-8/44312) (@shinadhingra18, Due: 8/30, Done: 8/27)
- [x] [Promoting on Rep Telegram channel](https://t.me/c/1020212813/24655) (@shinadhingra18 , Due: 9/2, Done: 8/27)
- [x] [Promoting on Reps-general mailing list](https://lists.mozilla.org/private/reps-general/2019-August/002455.html) (@shinadhingra18 , Due:  9/2, Done: 8/31)
- [x] [Promoting on Rep Telegram channel again](https://t.me/c/1020212813/24700) (@shinadhingra18 , Done: 9/6)
- [x] [Call for nominating on Twitter MozillaReps](https://github.com/mozilla/reps-tweets/issues/106) (@smsnobin77 , Due: 9/2, Done: 9/7)
- [ ] Call for nominating on Rep's weekly call (, Due: 9/5, Done: )

### Vote (1.5 weeks later)

- [x] Start the [voting procedure on Discourse #Mozillian](https://discourse.mozilla.org/t/voting-for-mozillian-of-the-month-august-end-at-9-22-15-00-utc/44831/) **from 9/9 to 9/22** open to all Mozillian (@irvin, Due: 9/9 15:00 UTC, Done: 9/9 17:50 UTC)
- [x] Link back to the voting thread from nominating thread (@irvin, Due: 9/9, Done: 9/9)
- [x] [Call for voting on Discourse #Rep category](https://discourse.mozilla.org/t/vote-for-mozillian-of-the-month-august-before-sunday/45373) (@irvin, Due: 9/12, Done: 9/20)
- [ ] Call for voting on Rep's call (@, Done: )
- [x] [Call for voting on Telegram Rep channel](https://t.me/c/1020212813/24917) (@irvin, Due: 9/12, Done: 9/20)
- [x] [Call for voting on Telegram Mozillian channel]()(@irvin, Due: 9/12, Done: 9/20)
- [x] [Call for voting on Twitter MozillaRep](https://github.com/mozilla/reps-tweets/issues/107) (@irvin, Due: 9/12, Done: 9/20)
- [x] [Call for voting on Slack Random channel](https://mozilla.slack.com/archives/C027LFU26/p1568984588118400) (@irvin, Due: 9/16, Done: 9/20)


### Announce (w4)

- [x] [Announce winner of Mozillian of the Month](https://discourse.mozilla.org/t/vishal-das-mozillian-of-the-month-august-2019/45984) and the following Rep's story on Discourse (@shinadhingra18 , Due: 9/22 15:00 UTC, Done: 9/30 14:00 UTC)
- [x] [Links to announce of Mozillian of the Month](https://discourse.mozilla.org/t/voting-for-mozillian-of-the-month-august-end-on-9-22-15-00-utc/44831/5) on voting thread (@irvin, Done: 10/1)
- [ ] [Announce the winner on Rep Telegram]() (, Due: 9/25, Done:)
- [x] [Announce the winner on Mozillian Telegram](https://t.me/mozillian/42052) (@irvin , Due: 9/25, Done: 10/1)
- [ ] [Announce the winner on Rep Twitter]()(, Due: 9/25, Done:
- [ ] [Announce the winner on Slack Random]() (Irvin, Due: 9/25, Done:)
- [ ] Collect swag shipping info (@irvin, Due: 9/30, Done:)
- [ ] Send the swag to Winner and Nominator (owner: @kelimuttu , Due:, Done: )
- [ ] [Send certification]() (Irvin, Due: 9/30, Done:)
- [ ] Collect [the stats](https://docs.google.com/document/d/1X_-mVXc0tNrbLK_nZZK2EMJZOgCjBLPO4K3UJZ0ZbgY/edit#heading=h.dzo7c9vvr20c) (owner: Irvin, Due: 9/30, Done: )
- [ ] Start new Github issue () (owner: Irvin, Due: 9/30, Done: )

**Comment by irvin** [comment]
## October action items (cancelled)

### Nominate (1st week of October) -10/10 15:00 UTC

- [x] [Ask Rep to start nominate for September Mozillian of the Month](https://discourse.mozilla.org/t/nomination-for-mozillian-of-the-month-august-starts-until-9-8/44312) (@shinadhingra18, Due: 10/1, Done: )
- [x] [Promoting on Rep Telegram channel](https://t.me/c/1020212813/24655) (@ , Due: 10/2, Done: )
- [x] [Promoting on Local Rep channel]() (@shinadhingra18 , Due: 10/2, Done: )
- [ ] [Promoting on Local Rep channel]() (@bobreyes , Due: 10/2, Done: )
- [ ] [Promoting on Local Rep channel]() (@smsnobin77 , Due: 10/2, Done: )
- [ ] [Promoting on Local Rep channel]() (@irvin , Due: 10/2, Done: )
- [ ] [Call for nominating on Twitter MozillaReps](https://github.com/mozilla/reps-tweets/issues/106) (@ , Due: 10/2, Done: )
- [ ] Call for nominating on Rep's weekly call (, Due: 10/4, Done: )

### Vote (1.5 weeks later) 10/11-10/26 15:00 UTC

- [ ] Start the [voting procedure on Discourse #Mozillian](https://discourse.mozilla.org/t/voting-for-mozillian-of-the-month-august-end-at-9-22-15-00-utc/44831/) **from 10/11 to 10/26** open to all Mozillian (@irvin, Due: 10/10 15:00 UTC, Done: )
- [ ] Link back to the voting thread from nominating thread (@irvin, Due: 10/11, Done: )
- [ ] [Call for voting on Discourse #Rep category](https://discourse.mozilla.org/t/vote-for-mozillian-of-the-month-august-before-sunday/45373) (@irvin, Due: 10/11, Done: )
- [ ] Call for voting on Rep's call (@, Due: 10/11, Done: )
- [ ] [Call for voting on Telegram Rep channel](https://t.me/c/1020212813/24917) (@ , Due: 10/12, Done: )
- [ ] [Call for voting on Telegram Mozillian channel]()(@, Due: 10/11, Done: )
- [ ] [Call for voting on Twitter MozillaRep](https://github.com/mozilla/reps-tweets/issues/107) (@ , Due: 10/12, Done: )
- [ ] [Call for voting on Slack Random channel](https://mozilla.slack.com/archives/C027LFU26/p1568984588118400) (@irvin, Due: 10/17, Done: )


### Announce (w4) 10/27-

- [ ] [Announce winner of Mozillian of the Month](https://discourse.mozilla.org/t/harsh-mehta-mozillian-of-the-month-july-2019/44307) and the following Rep's story on Discourse (@ , Due: 10/27 15:00 UTC, )
- [ ] [Links to announce of Mozillian of the Month](https://discourse.mozilla.org/t/voting-for-mozillian-of-the-month-july-end-at-8-25-15-00-utc/43730/6) on voting thread (@irvin, Done: )
- [ ] [Announce the winner on Rep Telegram]() (, Due: 10/27, Done:)
- [ ] [Announce the winner on Mozillian Telegram]() (, Due: 10/27, Done:)
- [ ] [Announce the winner on Rep Twitter]()(, Due: 10/27, Done:
- [ ] [Announce the winner on Slack Random]() (Irvin, Due: 10/27, Done:)
- [ ] Collect swag shipping info (@irvin, Due: 10/28, Done:)
- [ ] Send the swag to Winner and Nominator (owner: @kelimuttu , Due:, Done: )
- [ ] [Send certification]() (Irvin, Due: 10/30, Done:)
- [ ] Collect [the stats](https://docs.google.com/document/d/1X_-mVXc0tNrbLK_nZZK2EMJZOgCjBLPO4K3UJZ0ZbgY/edit#heading=h.dzo7c9vvr20c) (owner: Irvin, Due: 10/30, Done: )
- [x] Start new Github issue () (owner: Irvin, Due: 10/30, Done: )

**Comment by irvin** [comment]
Hi All, Due to the collapse at the same time as the Council vote, we're canceling this month's Mozillian of the Month campaign. We will return on 10/27 to start a new round, and welcome to preserve your nomination until then.

**Comment by irvin** [comment]
# Swag status
- [x] Pranshu Khanna (Feb, by Shina)
- [x] Diky Arga (March, by Yofie)
- [x] Allen Wang (April, by Irvin)
- [ ] [Harsh Mehta](https://bugzilla.mozilla.org/show_bug.cgi?id=1590509) (July, by Pranshu)
- [ ] [Vishal Das](https://bugzilla.mozilla.org/show_bug.cgi?id=1590508) (August, by Ranjith)

**Comment by irvin** [comment]
## November action items

### Nominate (1st week of November) 10/28-11/10 15:00 UTC

- [x] [Ask Rep to start nominate for October Mozillian of the Month](https://discourse.mozilla.org/t/nomination-for-mozillian-of-the-month-august-starts-until-9-8/44312) (@shinadhingra18 , Due: 10/28, Done: 11/1)
- [x] [Promoting on Rep Telegram channel](https://t.me/c/1020212813/25437) (@shinadhingra18  , Due: 10/29, Done: 11/1)
- [x] [Promoting on Local Rep channel]() (@shinadhingra18 , Due: 10/29, Done: )
- [ ] [Promoting on Local Rep channel]() (@bobreyes , Due: 10/29, Done: )
- [ ] [Promoting on Local Rep channel]() (@smsnobin77 , Due: 10/29, Done: )
- [x] [Promoting on Local Rep channel]() (@irvin , Due: 10/29, Done: 11/6)
- [x] [Call for nominating on Twitter MozillaReps](https://github.com/mozilla/reps-tweets/issues/111) (@irvin , Due: 10/29, Done: 11/6)
- [x] [Promoting on Rep Telegram channel(again)](https://t.me/c/1020212813/25477) (@irvin , Done: 11/6)
- [ ] Call for nominating on Rep's weekly call (, Due: 11/1, Done: )

### Vote (1.5 weeks later) 11/11-11/24 15:00 UTC

- [x] Start the [voting procedure on Discourse #Mozillian](https://discourse.mozilla.org/t/voting-for-mozillian-of-the-month-august-end-at-9-22-15-00-utc/44831/) **from 11/11 to 11/24** open to all Mozillian (@irvin, Due: 11/11 15:00 UTC, Done: 11/14 0:00)
- [x] Link back to the voting thread from nominating thread (@irvin, Due: 11/11, Done: 11/14)
- [ ] [Call for voting on Discourse #Rep category](https://discourse.mozilla.org/t/vote-for-mozillian-of-the-month-august-before-sunday/45373) (@irvin, Due: 11/17, Done: )
- [ ] Call for voting on Rep's call (@, Due: 11/14, Done: )
- [x] [Call for voting on Telegram Rep channel](https://t.me/c/1020212813/25606) (@ , Due: 11/12, Done: 11/14)
- [x] [Call for voting on Telegram Mozillian channel](https://t.me/mozillian/43276)(@, Due: 10/12, Done: 10/14)
- [ ] [Call for voting on Twitter MozillaRep](https://github.com/mozilla/reps-tweets/issues/107) (@ , Due: 10/16, Done: )
- [ ] [Call for voting on Telegram Rep channel (again)](https://t.me/c/1020212813/24917) (@ , Due: 11/20, Done: )
- [ ] [Call for voting on Telegram Mozillian channel (again)](https://t.me/mozillian/43276)(@, Due: 11/20, Done: )
- [x] [Call for voting on Slack Random channel](https://mozilla.slack.com/archives/C027LFU26/p1573663560092100) (@irvin, Due: 11/14, Done: )


### Announce (w4) 11/25-

- [ ] [Announce winner of Mozillian of the Month](https://discourse.mozilla.org/t/harsh-mehta-mozillian-of-the-month-july-2019/44307) and the following Rep's story on Discourse (@ , Due: 11/25 15:00 UTC, )
- [ ] [Links to announce of Mozillian of the Month](https://discourse.mozilla.org/t/voting-for-mozillian-of-the-month-july-end-at-8-25-15-00-utc/43730/6) on voting thread (@irvin, Done: )
- [ ] [Announce the winner on Rep Telegram]() (, Due: 11/24, Done:)
- [ ] [Announce the winner on Mozillian Telegram]() (, Due: 11/24, Done:)
- [ ] [Announce the winner on Rep Twitter]()(, Due: 11/25, Done:
- [ ] [Announce the winner on Slack Random]() (Irvin, Due: 11/25, Done:)
- [ ] Collect swag shipping info (@irvin, Due: 11/30, Done:)
- [ ] Send the swag to Winner and Nominator (owner: @kelimuttu , Due:, Done: )
- [ ] [Send certification]() (Irvin, Due: 11/30, Done:)
- [ ] Collect [the stats](https://docs.google.com/document/d/1X_-mVXc0tNrbLK_nZZK2EMJZOgCjBLPO4K3UJZ0ZbgY/edit#heading=h.dzo7c9vvr20c) (owner: Irvin, Due: 11/30, Done: )
- [ ] Start new Github issue () (owner: Irvin, Due: 11/30, Done: )
