### ISSUE TITLE
OKR 2019 H2 - Yofie

### ISSUE THREAD

**Issue by yofiesetiawan** [mozilla/Reps#388]
## Goal: 
KR: More than 80% of the reps are reporting that they know what MDM is about.

## Related Issues & Links: 

Key Result Planning Document
https://docs.google.com/document/d/1oyLIQZTDWxYCPa_sNFyiDHsHbC6TYdfNDS773BYBpLQ

Mentor Training for MDM H2 2019
https://docs.google.com/presentation/d/1o03BnDfPOC8bO6r6H2CHjjkRI4QFrLL2L4C4qBGxLGw/edit?usp=sharing

Survey to Understand MDM Awareness
https://forms.gle/UtBE9KQLz31HDet8A

Blogpost Discourse
https://discourse.mozilla.org/t/mission-driven-mozillians-2019-h2-update/45009

## Roles:
Responsible: Yofie
Accountable: Yofie & Mayur
Supporting: Rep Councils & Peers
Consulted: Rep Councils & Peers
Informed: Rep Councils & Peers

## Milestone 1: Promote the value of MDM via the blogpost
- [x] Draft blogpost (Due: Aug 27th) 
- [x] Ask Reps Council & Peers for review (Due: Sep 10th) 
- [x] Release the blogpost also on discourse (Due: Sep 12th)
- [x] Get feedbacks (Due: Sep 24th)

## Milestone 2: Have a section on reps call once a month to talk about MDM and MDM portal 
- [x] Collecting MDM updates each month 
- [x] Share on reps call each month
- [x] Get feedbacks

## Milestone 3: Run a call with the mentors to talk about MDM and how they talk about it with their mentees
- [x] Draft presentation material for mentor training. (Due: Oct 8th) 
- [x] Decide a time to do the call with mentors (40) (Due: Oct 15th) 

## Milestone 4: Run a survey to ensure that Reps are on the 80%
- [x] Draft the questions I want to ask (Due: Oct 15st) 
- [x] Send to council for feedback (Due: Oct 15st) 
- [x] Create the survey (Due: Oct 22nd) 
- [x] Send the message for feedback to Konstantina (Due: Oct 22nd) 
- [x] Post the message on discourse (Due: Oct 24th) 
- [x] Close the survey (Due: Nov Oct 31st) 
- [x] Share with the council (Due: Nov 7th) 
- [x] Post your results on discourse (Due: Nov 14th)

**Comment by couci** [comment]
@couci @nukeador  @yomanpatil and Shahid are reviewing the post, review ends on the Wednesday 12th. https://docs.google.com/document/d/1gRFI_xK2lHwzasg2rd2vaagEpXZSxphoDBbjL3AGCCY/edit

**Comment by couci** [comment]
Yofie is working on the presentation for mentors, mdm portal update will be co hosted for this weeks reps call

**Comment by shahbaz17** [comment]
Should I made changed to Milestones? as most of them are completed now
@couci

**Comment by couci** [comment]
yes please do @shahbaz17

**Comment by shahbaz17** [comment]
Update:

I will be scheduling a call with all the mentors this month. After that, I will be creating the Survey and the result will be shared in the Council meeting.

**Comment by shahbaz17** [comment]
I have scheduled two mentor's call and the report was presented to Council in Council meeting[2020-03-10](https://reps.mozilla.org/e/reps-council-weekly-meeting-2020-3-10/) and the details can be found [here](https://docs.google.com/document/d/1GnUZBhZmEDAZufj78j2IjAovX4CMwTSUVG4OR1QhXvY/edit).

The Report will be shared with the team working on Mentors listed on [this discourse post](https://discourse.mozilla.org/t/improve-the-reps-program-please-help-us-by-driving-change/55273).

Thank you.
