### ISSUE TITLE
OKR 2019 H2 - Getting inactive Reps re-activate

### ISSUE THREAD

**Issue by irvin** [mozilla/Reps#390]
## Goal: 
10% of inactive Reps are getting reactivated via the campaigns

## Related Issues & Links: 
#385 , 
Planning doc - https://docs.google.com/document/d/1P2UxSOtQFlC0ohd01fxJjg-1EUylV5dmnFWc2uzwIb8/edit?usp=sharing
Discourse discusstion - https://discourse.mozilla.org/t/plan-to-getting-inactive-reps-re-active-via-campaigns-as-okr-for-2019-h2/44309/2

## Roles:

Responsible: @irvin
Accountable:  
Supporting: 
Consulted: @couci
Informed: 

## Planning Timeline

Milestone 1: Get the numbers and list of inactive Reps - Until the first week of September
Milestone 2: Establish bridge with the inactive Rep for the first time - 2 weeks / W3 of Sep
Milestone 3: Reach to inactive Reps for first campaigns and check the numbers of re-active - 2 weeks / W1 of Oct
Milestone 4: Get the final numbers - 1 week / Mid Oct
Milestone 5: Graduate the in-active rep to alumni if they want - 1 week / Late Oct

### Milestone 1: Get the numbers and list of inactive Reps
- [x] [List reps who is inactive (6M) to spreadsheet](https://docs.google.com/spreadsheets/d/1x5YfxZSINc6pUuJTJSJ3A8EiZwsxYxXGW6850jYCvlQ/edit?pli=1#gid=2119505810) (84 ppls)
### Milestone 2: Establish bridge with the inactive Rep for the first time 
- [x] [Draft a mail to inactive rep to ask about their status](https://docs.google.com/document/d/1xJf0s_OtX_CmzY10GJFgAm819xd0EPH6e-rgz1P4p0w/edit), and provide some items to do
- [x] Send mail to council for check during council meeting
- [x] Send the mail (done: 10/22)
- [x] Wait one week, check if they had update the profile
- [ ] Collect the bounced mail and re-send to their login mail (and ask them to udpate the personal file's email column)
- [ ] (Still inactive) Collect inactive rep’s telegram account to list
- [ ] Ping them to ask about receiving mail or not (and getting connect with them by IM)

### Milestone 3: Reach to inactive Reps for first campaigns and check the numbers of re-active
- [x] Draft the mail after any of the campaigns timeline reveal
- [ ] Share the mail to review during council meeting
- [x] Send the mail
### Milestone 4: Get the final numbers
- [ ] Check how many reps are no longer in-active from list 
- [ ] Calculate the numbers
### Milestone 5: Graduate the in-active rep to alumni if they want 
- [ ] Collect the list of in-active rep who want to graduate
- [ ] Move them to Alumni, send the certification

**Comment by Mte90** [comment]
Seems that the document is public and everyone can edit it

**Comment by irvin** [comment]
@Mte90 which docs? both mail draft and list has privilege requirement

**Comment by Mte90** [comment]
The planning doc, say that `everyone with the link can see it`

**Comment by couci** [comment]
@Mte90 but that's by design, we don't have anything confidential in there so we want to give visibility to the Reps on what we are working on

**Comment by irvin** [comment]
Just sent the first mail to inactive rep, there are total 84 reps.

**Comment by irvin** [comment]
Will wait for one week to see if any of they response.

**Comment by irvin** [comment]
so far we have 10 reps responsed, 2 of them would like to graduate.

**Comment by irvin** [comment]
I had sent another contact mail to inactive rep and provide some activity to do 
<img width="903" alt="截圖 2019-11-20 上午2 34 30" src="https://user-images.githubusercontent.com/165936/69175276-69da1800-0b3e-11ea-9ed5-ed969033fcf6.png">

**Comment by irvin** [comment]
Status so far,
 
Listed 84 Reps (inactive > 6m)
11 responsed
4 updated
3 of them plan to leave

**Comment by irvin** [comment]
Status so far,

Listed 84 Reps (inactive > 6m)

30/84 responded / updated (35%)
9 updated activity (10.7%, reached the goal)
5 plan to leaving to Alumni

**Comment by irvin** [comment]
updated: 
Listed 84 Reps (inactive > 6m)

33/84 responded / updated (39%) 
12 updated activity (14.2%, reached the OKR goal)
5 plan to leaving > moved to alumni, and cert sent on 9 Jan. 

Next actions: 
31 people is inactive > 12M and still not response
I will give them a notice, and move to alumni after two weeks (Feb 1)
draft mail - https://docs.google.com/document/d/1mnpajQLEqxta5JgYNl6YxiQtvTBFA_J9fvKtMmYX5S4/edit?usp=sharing

**Comment by irvin** [comment]
I think we can close this and continue on #385
