### ISSUE TITLE
OKR 2019 H2 - Onboarding

### ISSUE THREAD

**Issue by yulireyji** [mozilla/Reps#391]
## Goal:  
90% of the new onboarded Reps are reporting that are ready to become local leaders in their community due to their onboarding training

## Related Issues & Links: 
https://docs.google.com/document/d/11eq2C_5Aw4LoTjK2vh8heSxuAyeKj25xsFSYYs0hBqw/edit#heading=h.et8imi643ahc

## Roles:

Responsible: Yuli

Accountable: Yuli

Supporting: Konstantina

Consulted: Rep Councils & Peers

Informed: Rep Councils & Peers

## Milestone 1: Revise the current onboarding
- [x] Review the current webinar and see if the video has all the new information.
- [x] Talk with the current onboarding team for your plan and ask them if they want to participate.
- [ ] Ensure that the new training has code of conduct training.
- [ ] Create an online course based the webinar.
- [ ] Create a mandatory meeting for the new Reps where they take tasks.
- [ ] Send your plan to the council for review.

## Milestone 2: Create an onboarding survey for the reps that have been onboarded
- [ ] Create a survey.
- [ ] Pass it from the onboarding team and the council for feedback.
- [ ] Start posting it to the reps that have been onboarded.
- [ ] Document the changes of onboarding on the wiki.

**Comment by couci** [comment]
Video has information we need but needs update to include Mission Driven Mozillians program, campaigns and CPG

**Comment by balapandu222-zz** [comment]
@couci Is there any specific onboarding time period? Based on that we need to plan the new structure for implementing their strategies.

**Comment by couci** [comment]
hey @balapandu222 currently it's 3 months. I think it's better that we first design and base on our needs we decide the time rather the other way around.

**Comment by balapandu222-zz** [comment]
@couci @yulireyji if possible please schedule a call with the onboarding review team. Based on everyone's views, we can decide whether we should revamp the orientation period structure or not.
Thank you!

**Comment by couci** [comment]
Onboarding outline here: https://docs.google.com/document/d/1PHxG1Dz_jaEZ8TrKgHI14i2P7ecGh9_yshhQ6Hf2kg8/edit

**Comment by asdofindia** [comment]
@couci I disagree with this statement in the document:

> We have seen that while the first part “application” works well, the second part, marked as onboarding feels passive without giving the opportunities to new Reps to be trained and share their work.

The first part, the "application" does not work that very well. There is vagueness in the selection criteria and the application/screening process is not inclusive to people from various backgrounds and different cultures. I've written about these at https://discourse.mozilla.org/t/improving-application-and-on-boarding/48071?u=asdofindia in detail. If you want me to paste the same points here (as you've requested on that thread), I can do so.

**Comment by couci** [comment]
@asdofindia I understand that there are improvements needed. I don't agree with the statement: "inclusive to people from various backgrounds and different cultures" but that's your opinion and you are entitled to this.
As indicated in discourse please open a new issue. I would encourage you that when you are pointing issues, suggest alternatives on how those can be fixed.
