### ISSUE TITLE
OKR 2019 H2 - Prathamesh - Elections

### ISSUE THREAD

**Issue by prathameshchavan** [mozilla/Reps#393]
## Goal: 
KR : More than 70% reps are voting in autumn elections

## Related Issues & Links: 
[https://docs.google.com/document/d/13JmPEit_Y7WqFSpD4_uxY-dLt2U4dYZzN5vaa00Ms0w/edit?usp=sharing](https://docs.google.com/document/d/13JmPEit_Y7WqFSpD4_uxY-dLt2U4dYZzN5vaa00Ms0w/edit?usp=sharing)

## Roles:

Responsible: Prathamesh

Accountable: Prathamesh

Supporting: Rep Council

Consulted: Rep Council

Informed: Rep Council

## Milestone 1: Making aware Reps that elections are happening
- [x] Get the timeline of the elections from Ioana
- [x] List the channels to target
- [x] Create a template on what to send in each channel - content creation
- [x] Coordinate with Ioana with the timeline

## Milestone 2: Making Reps aware of the timeline
- [x] Send the content to the channels
- [x] Follow up with another round of content 

## Milestone 3:  Heavy engagement with people when the voting starts
- [x] Follow up on the channels once the voting starts
- [x] Track the number of people voting each day
- [x] Target the Reps who are yet to respond
- [x] Follow up on the channel

**Comment by couci** [comment]
once the townhalls and discourse are over @prathameshchavan will start communications to press for voting

**Comment by ioana-chiorean** [comment]
Thanks for the help here! 🎉

**Comment by prathameshchavan** [comment]
https://docs.google.com/document/d/1MbQ12GpXLIEGuv20PkXSYKkkgtFfbMkfyZSmJbHIZc8/edit?usp=sharing

**Comment by Mte90** [comment]
That doc is public and configured that everyone can edit

**Comment by MichaelKohler** [comment]
@prathameshchavan you might be interested in https://michaelkohler.github.io/reps-voting-analysis/#/

**Comment by prathameshchavan** [comment]
The Elections did not meet the expected voting % and I am sharing my observations for the figures to be low :
- Access to the Reps portal
Few of the Reps are not able to access the Reps portal due to the 2FA. Not everyone's 2FA is working as expected and hence many of the Reps were not able to login and vote.

- Unaware about the Elections
The Elections dates were announced and published on multiple platforms (Discourse, Telegram, emails, etc.) but some of the Reps were unaware of the Elections. The underlying reason for this is that the Reps have been divided and spread across multiple communication platforms and an absence of a central Mozilla governed platform adds to it. 

- Lack of interest
Few of the Reps felt that the nominees contesting the elections were not suitable candidates which they would love to vote and hence few of the Reps opted to stay away from the voting. Few of the Reps are not happy with the existing Reps program directions and feel left-out; such kind of factors have also added to the discouragement to vote.

- Inactive Reps
The Reps program is currently having a lot of inactive Reps who have not reported there activities for a long time. The inactive Reps to active Reps proportion is significant which has contributed for the dipping of the overall voting % .

**Comment by Mte90** [comment]
Some of those are technical issues that can be fixed, others are mainly the issue that reps are not aligned with what his doing the program.

So I think that is just matter of priorities. Maybe is better to move this discussion on Discourse?
