### ISSUE TITLE
More activities related to MDM campaigns are reported on reps portal (30% more reporting) 

### ISSUE THREAD

**Issue by yomanpatil** [mozilla/Reps#394]
**Name of the key result:
More activities related to MDM campaigns are reported on reps portal (30% more reporting)** 

**Steps**
**Add the milestones in order to reach your key result:**
Milestone 1: Check the current status so we can define 30% more
Milestone 2: Promotion of campaigns to the Reps 
Milestone 3: Promotion of reporting to the Reps
Milestone 4: Check the revised status of the reported activities

**2) How much time do you need to achieve one milestone in weeks?**

Milestones | Time needed
-- | --
Milestone 1: Check the current status so we can define 30% more | 2 weeks
Milestone 2: Promotion of campaigns to the Reps | 4 weeks
Milestone 3: Promotion of reporting to the Reps | 4 weeks
Milestone 4:Check the revised status of the reported activities | 2 weeks

**3) Break down your milestone on to do’s. What do you need to do to achieve that milestone?**

**Milestone 1:** Check the current status so we can define 30% more
To do’s 

- [ ] Get data from Michael
- [ ] Make a report of the data
- [ ] After we get the number , set a milestone figure (30% more of the data received) 

**Milestone 2:** Promotion of campaigns to the Reps

- [x] Make a list of channels for promotion
- [x] Draft content for the campaign promotion.
- [x] Create comms plan and get approved from Konstantina
- [x] Get draft approved from Konstantina
- [x] Set data for campaign promotion
- [x] Shoot campaign
- [ ] Study metrics

**Milestone 3:** Promotion of reporting to the Reps

- [x] Make a list of channels for promotion
- [x] Draft content for the reporting of MDM activities promotion.
- [x] Create comms plan and get approved from Konstantina
- [x] Get draft approved from Konstantina
- [x] Set data for campaign promotion
- [x] Shoot campaign
- [ ] Study metrics

**Milestone 4:** Check the revised status of the reported activities

- [ ] Create metrics report of different campaigns
- [ ] Compare it with past metrics
- [ ] Create results report
- [ ] Publish the results 
- [ ] If results are unsatisfactory redo milestone 2 and 3

**4) Post your plan on github - it will help you track everything and give visibility to the rest of the Reps**

- [x] Done

**5) Make an announcement of your plan in discourse and let Reps know - maybe someone wants to help you, give them the chance to say so**

- [ ] Done

**Comment by yomanpatil** [comment]
@yofiesetiawan Will need your help in this.

**Comment by yomanpatil** [comment]
Channels for promotion

- [ ] 1. Telegram
- [ ] 2. Mailing list
- [ ] 3. Discourse 
- [ ] 4. Twitter
- [ ] 5. Instagram reps account

**Comment by yomanpatil** [comment]
Research on the data

https://reps.mozilla.org/api/remo/v1/activities/
https://reps.mozilla.org/reports/?query=Campaigns
https://reps.mozilla.org/reports/new/

**Comment by couci** [comment]
Mayur is getting the data under initiative: campaigns

**Comment by yomanpatil** [comment]
Training via Reps weekly call done on 5th Dec

**Comment by yomanpatil** [comment]
Update

**Status:** Not completed
**Blocked:** Not much activities in the past, Hence we were unable to see/calculate the increase in the reporting done by the MDMs
**Next:** Can be included in the next OKR
