### ISSUE TITLE
OKR 2019 H1 - Reactivation through campaigns

### ISSUE THREAD

**Issue by Penrosee** [mozilla/Reps#395]
## Goal: 
3 communities that haven’t participated before in campaigns are now joining campaigns regularly 

## Related Issues & Links: 
https://docs.google.com/document/d/1WhnLuPX8bsMQRxjAVXpbveJNjoqE-EVmFtcVdjYrk0Y/edit#
#

## Roles:

Responsible: Monica

Accountable: Monica

Supporting: Konstantina

Consulted: Rep Councils & Peers

Informed: Rep Councils & Peers

## Milestones: 
- [x] Identify inactive communities
- [x] Communicate with leaders and people active within these communities (individually) 
- [ ] Attempt to bring together various community leaders.
- [ ] Share information about the campaign and follow up to organize an event.
- [ ] Make a publication on the Reps blog informing about the participation of new communities

**Comment by felipez3r0** [comment]
During the last month, I started talking with Mozillians to gather information about this.
I created [a document to input this information](https://docs.google.com/document/d/1K5J-DJGWGKHFl5iBAtAbw8E7XUNNOzjXhKrUnWC9EO0/edit?usp=sharing).

I plan to complete the document in January (after all the conversations).
Right now, I'm focusing on talking with 4 Mozillians (3 Reps, 1 Non-rep) from LATAM and Africa, after this talk I'll propose some solutions for the raised issues.

**Comment by felipez3r0** [comment]
I shared some proposals at the document; they are drafts, they need more work and improvement, but they can be starting points to think about what we can change to solve those raised issues.

**Comment by felipez3r0** [comment]
### Update
**Status:** 
- Not completed

**Blocked:**
- Lack of information from the previous work, everything started from scratch when the council changed.

**Next:**
- Some issues raised during the interviews are related to the new OKRs: Reps Weekly Call (LATAM time - communication) and information about Mozilla direction/decision.
- More information here: [Inactive communities findings](https://docs.google.com/document/d/1K5J-DJGWGKHFl5iBAtAbw8E7XUNNOzjXhKrUnWC9EO0/edit)

**Comment by MichaelKohler** [comment]
I'm closing this. Please open specific issues if necessary. Thanks!
